g60_gps_odom_alignment:
  ros__parameters:
    fix_topic: /fix
    odom_topic: /odometry_horizon
    fix_odom_topic: /fix_odom
    fix_odom_frame_id: gps
    output_frame: world
    transform_path: ''
    max_time_delta: 0.15
    calibration_pairs: 30
    min_calibration_displacement: 1.0
    max_points: 10000

g60_fix_to_polyline:
  ros__parameters:
    fix_topic: /fix
    output_filename: gps_trajectory.ovjsn
    max_points: 100000
    polyline_name: fix
    reset_service: reset_polyline

g60_fix_odom_to_polyline:
  ros__parameters:
    fix_topic: /fix_odom
    output_filename: fix_odom_trajectory.ovjsn
    max_points: 100000
    polyline_name: fix_odom
    reset_service: reset_polyline_odom
