g60_serial:
  ros__parameters:
    port: /dev/g60_gnss
    baud: 9600
    timeout_sec: 0.2
    reconnect_sec: 2.0
    frame_id: gps
    time_ref_source: g60_gnss
    use_rmc_fix: false
    publish_raw_nmea: false
    raw_nmea_topic: /nmea_sentence
