gnss_transform:
  ros__parameters:
    transform_path: ''
    input_topic: /odometry_horizon
    output_topic: /fix_from_odom
    rtk_topic: ''
    rtk_output_topic: /odometry_from_rtk
    rtk_fix_topic: /fix_from_rtk
    rtk_frame_id: gps
    rtk_child_frame_id: rtk_gps
    enable_gps_goal_action: true
    gps_goal_action: /set_gps_goal
    navigation_action: /multi_map_navigate_to_pose
    next_goal_policy_service: /next_goal_policy
    action_server_wait_sec: 5.0
    next_goal_policy_wait_sec: 5.0
    action_result_timeout_sec: 0.0

